
logging:
  level:
    root: info
    md.utm2026.mvc: debug
    #org.springframework.web: debug



spring:
  application:
    name: mvc-demo
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

app:
  upload-dir: uploads
  api-key: 123456
  api-key-header: X-AUTH-KEY

